const ERROR_CODES = Object.freeze({
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  DESKTOP_ONLY_FEATURE: 'DESKTOP_ONLY_FEATURE',
  MODEL_INVALID: 'MODEL_INVALID',
  PYTHON_ENV_INVALID: 'PYTHON_ENV_INVALID',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  FS_PERMISSION_DENIED: 'FS_PERMISSION_DENIED',
  BACKEND_BOOT_FAILED: 'BACKEND_BOOT_FAILED',
  DIAGNOSTICS_EXPORT_FAILED: 'DIAGNOSTICS_EXPORT_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CONFLICT: 'CONFLICT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  BAD_REQUEST: 'BAD_REQUEST'
});

const DEFAULT_HINTS = Object.freeze({
  ROUTE_NOT_FOUND: '请确认应用已升级到最新版本并重试。',
  DESKTOP_ONLY_FEATURE: '该功能仅支持桌面版，请在 Electron 客户端中使用。',
  MODEL_INVALID: '请检查模型文件路径、格式和完整性。',
  PYTHON_ENV_INVALID: '请在设置中确认 Python 路径并检查依赖是否已安装。',
  PROJECT_NOT_FOUND: '项目可能已删除或路径无效，请刷新项目列表。',
  VALIDATION_ERROR: '请检查输入参数后重试。',
  FS_PERMISSION_DENIED: '请确认目录可写、文件未被占用，并以合适权限运行程序。',
  BACKEND_BOOT_FAILED: '后端启动失败，请查看诊断信息并修复后重启应用。',
  DIAGNOSTICS_EXPORT_FAILED: '诊断包导出失败，请检查日志目录权限并重试。',
  INTERNAL_ERROR: '发生内部错误，请重试或导出诊断包。',
  CONFLICT: '请求与最新数据冲突，请刷新后重试。',
  UNAUTHORIZED: '当前请求未授权。',
  FORBIDDEN: '当前操作被拒绝，请检查权限。',
  BAD_REQUEST: '请求参数不合法，请检查后重试。'
});

const RETRYABLE_CODES = new Set([
  ERROR_CODES.INTERNAL_ERROR,
  ERROR_CODES.BACKEND_BOOT_FAILED
]);

module.exports = {
  ERROR_CODES,
  DEFAULT_HINTS,
  RETRYABLE_CODES
};
